/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "platforms_types.h"
#define RCC_BASE 		0x040021000
#define PORTA_BASE 		0x040010800
#define RCC_CR			*(vuint32_t*) (RCC_BASE+0x00)
#define RCC_CFGR 		*(vuint32_t*) (RCC_BASE+0x04)
#define RCC_APB2ENR 	*(vuint32_t*) (RCC_BASE+0x18)
#define GPIOA_CRH 		*(vuint32_t*) (PORTA_BASE+0x04)
#define GPIOA_ODR 		*(vuint32_t*) (PORTA_BASE+0x0c)

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	// RCC

	RCC_CFGR |= (0b0110 <<18) ;
	RCC_CFGR |= (0b100 <<8) ;
	RCC_CFGR |= (0b101 <<11) ;
	RCC_CFGR |= (0b10 <<0) ;;

	RCC_CR |= (1<<24) ;
	RCC_APB2ENR |= 1<<2;
	// GPIOA
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	for (;;)
	{
		GPIOA_ODR |= 1<<13 ;
		for (int i=0;i<5000;i++);
		GPIOA_ODR &= ~(1<<13) ;
		for (int i=0;i<5000;i++);
	}
	return 0;
}
