#ifndef DIO_PRIVATE_H_
#define DIO_PRIVATE_H_



#define Conc(b7,b6,b5,b4,b3,b2,b1,b0)			Conc_help(b7,b6,b5,b4,b3,b2,b1,b0)
#define Conc_help(b7,b6,b5,b4,b3,b2,b1,b0)		0b##b7##b6##b5##b4##b3##b2##b1##b0

#define DDRAVAL Conc(PORTA_PIN7_DIR,PORTA_PIN6_DIR,PORTA_PIN5_DIR,PORTA_PIN4_DIR,PORTA_PIN3_DIR,PORTA_PIN2_DIR,PORTA_PIN1_DIR,PORTA_PIN0_DIR)
#define DDRBVAL Conc(PORTB_PIN7_DIR,PORTB_PIN6_DIR,PORTB_PIN5_DIR,PORTB_PIN4_DIR,PORTB_PIN3_DIR,PORTB_PIN2_DIR,PORTB_PIN1_DIR,PORTB_PIN0_DIR)
#define DDRCVAL Conc(PORTC_PIN7_DIR,PORTC_PIN6_DIR,PORTC_PIN5_DIR,PORTC_PIN4_DIR,PORTC_PIN3_DIR,PORTC_PIN2_DIR,PORTC_PIN1_DIR,PORTC_PIN0_DIR)
#define DDRDVAL Conc(PORTD_PIN7_DIR,PORTD_PIN6_DIR,PORTD_PIN5_DIR,PORTD_PIN4_DIR,PORTD_PIN3_DIR,PORTD_PIN2_DIR,PORTD_PIN1_DIR,PORTD_PIN0_DIR)

#define PORTAVAL Conc(PORTA_PIN7_Val,PORTA_PIN6_Val,PORTA_PIN5_Val,PORTA_PIN4_Val,PORTA_PIN3_Val,PORTA_PIN2_Val,PORTA_PIN1_Val,PORTA_PIN0_Val)
#define PORTBVAL Conc(PORTB_PIN7_Val,PORTB_PIN6_Val,PORTB_PIN5_Val,PORTB_PIN4_Val,PORTB_PIN3_Val,PORTB_PIN2_Val,PORTB_PIN1_Val,PORTB_PIN0_Val)
#define PORTCVAL Conc(PORTC_PIN7_Val,PORTC_PIN6_Val,PORTC_PIN5_Val,PORTC_PIN4_Val,PORTC_PIN3_Val,PORTC_PIN2_Val,PORTC_PIN1_Val,PORTC_PIN0_Val)
#define PORTDVAL Conc(PORTD_PIN7_Val,PORTD_PIN6_Val,PORTD_PIN5_Val,PORTD_PIN4_Val,PORTD_PIN3_Val,PORTD_PIN2_Val,PORTD_PIN1_Val,PORTD_PIN0_Val)

//PORT A
#define PORTA_REG		*((vuint8_t*)(0x3B))
#define DDRA_REG		*((vuint8_t*)(0x3A))
#define PINA_REG		*((vuint8_t*)(0x39))
//PORTB					 
#define PORTB_REG		*((vuint8_t*)(0x38))
#define DDRB_REG		*((vuint8_t*)(0x37))
#define PINB_REG		*((vuint8_t*)(0x36))
//PORTC					 
#define PORTC_REG		*((vuint8_t*)(0x35))
#define DDRC_REG		*((vuint8_t*)(0x34))
#define PINC_REG		*((vuint8_t*)(0x33))
//PORTD					 
#define PORTD_REG		*((vuint8_t*)(0x32))
#define DDRD_REG		*((vuint8_t*)(0x31))
#define PIND_REG		*((vuint8_t*)(0x30))


#endif /* PRIVATE_H_ */