/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may platforms_types.hobtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "platforms_types.h"
#define RCC_BASE 		0x040021000
#define PORTA_BASE 		0x040010800
#define RCC_APB2ENR 	*(vuint32_t*)(RCC_BASE+0x18)
#define GPIOA_CRH 		*(vuint32_t*)(PORTA_BASE+0x04)
#define GPIOA_ODR 		*(vuint32_t*)(PORTA_BASE+0x0c)

typedef union{
	vuint32_t allfields;
	struct{
		vuint32_t reserved:13;
		vuint32_t P_13:1;
	}Pin;                                           
}R_ODR_t;

volatile R_ODR_t* R_ODR = (R_ODR_t*) (PORTA_BASE+0x0c);
int main(void)
{
	RCC_APB2ENR |= 1<<2;
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
	for (;;)
	{
		GPIOA_ODR |= 1<<13 ;
		for (int i=0;i<5000;i++);
		GPIOA_ODR &= ~(1<<13) ;
		for (int i=0;i<5000;i++);
	}
	return 0;
}
