/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "platforms_types.h"
//RCC
#define RCC_BASE 		0x40021000
#define RCC_APB2ENR 	*(vuint32_t*)(RCC_BASE+0x18)
//GPIO
#define PORTA_BASE 		0x40010800
#define GPIOA_CRH 		*(vuint32_t*)(PORTA_BASE+0x04)
#define GPIOA_CRL 		*(vuint32_t*)(PORTA_BASE+0x00)
#define GPIOA_ODR 		*(vuint32_t*)(PORTA_BASE+0x0c)
//EXTI
#define EXTI_Base		0x40010400
#define EXTI_IMR 		*(vuint32_t*)(EXTI_Base+0x00)
#define EXTI_RTSR 		*(vuint32_t*)(EXTI_Base+0x08)
#define EXTI_PR 		*(vuint32_t*)(EXTI_Base+0x14)

//AFIO
#define AFIO_Base		0x40010000
#define AFIO_EXTICR1 	*(vuint32_t*)(AFIO_Base+0x14)

// NVIC Set enable
#define NVIC_EXTIE0		*(vuint32_t*)(0xE000E100)

void clock_init()
{
	RCC_APB2ENR |= (1<<2);
	RCC_APB2ENR |= (1<<0);
}

void GPIO_init()
{
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	//PIN A0 Floating Input
	GPIOA_CRL |= (1<<2);
}

int main(void)
{
	clock_init();
	GPIO_init();

	//EXTI0 TO PortA0
	AFIO_EXTICR1 = 0;

	//Enable Rising trigger
	EXTI_RTSR |= (1<<0);

	//Enable EXTI0
	EXTI_IMR |= (1<<0);


	NVIC_EXTIE0 |= (1<<6);

	while(1);

	return 0;
}

void EXTI0_IRQHandler (void)
{
	GPIOA_ODR ^=(1<<13) ;

	//Clear pending request for line 0
	EXTI_PR |= (1<<0);
}
